name: Build and Deploy

on:
  push:
    branches:
      - main  # Trigger on push to main
  workflow_dispatch:   # Allow manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout this repository
    - name: Checkout this repo
      uses: actions/checkout@v3

    # Checkout the external repository
    - name: Checkout cookbookgen
      uses: actions/checkout@v3
      with:
        repository: nelsongillo/cookbookgen
        path: cookbookgen
    
    # Install go
    - uses: actions/setup-go@v6
      with:
        go-version: '1.25'

    # Build the executable
    - name: Build cookbookgen
      run: |
        cd cookbookgen
        make build

    # Run the tool to generate HTML
    - name: Generate HTML
      run: |
        ./cookbookgen/out/cookbookgen --recipes . --output ./public

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
